config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :twits
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "twits#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twit.rb
class Twit < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
    def sign_up_params 
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params 
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_action :set_twit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,expect: [:index, :show]
  # GET /twits or /twits.json
  def index
    @twits = Twit.all.order("created_at DESC")
    @twit = Twit.new
  end

  # GET /twits/1 or /twits/1.json
  def show
  end

  # GET /twits/new
  def new
    @twit = Twit.new
  end

  # GET /twits/1/edit
  def edit
  end

  # POST /twits or /twits.json
  def create
    @twit = Twit.new(twit_params)

    respond_to do |format|
      if @twit.save
        format.html { redirect_to root_path, notice: "Twit was successfully created." }
        format.json { render :show, status: :created, location: @twit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twits/1 or /twits/1.json
  def update
    respond_to do |format|
      if @twit.update(twit_params)
        format.html { redirect_to twit_url(@twit), notice: "Twit was successfully updated." }
        format.json { render :show, status: :ok, location: @twit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twits/1 or /twits/1.json
  def destroy
    @twit.destroy

    respond_to do |format|
      format.html { redirect_to twits_url, notice: "Twit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twit
      @twit = Twit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twit_params
      params.require(:twit).permit(:twit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tw</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
      <%if flash[:alert] %>
        <div class="notification is-primary global-notification">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>
      <nav class="navbar is-info">
        <div class="navbar-brand">
          <%= link_to root_path, class:"navbar-item" do %>
            <h1 class="title is-5">Twit</h1>
          <% end %>
          <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
          </div> 
        </div>
        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'New Twit', new_twit_path, class:"button is-info is-inverted" %>
              </p>
              <p class="control">Sign Up</p>
            </div>
          </div>
         </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/twits/_feed.html.erb
<div class="column is-half">
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </p>
        </figure>
        <div class="media-content">
            <%= render 'twits/form' %>
        </div>
    </article>


<% @twits.each do |twit| %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong>Necmi Gunduz</strong><br>
                    <small>@necm_gun</small><br>
                    <p><%= twit.twit %></p>
                </div>
                <div class="level">
                    <div class="level-left is-mobile">
                    <%= link_to twit, class:"level-item" do %>
                        <span class="icon"><i class="fa fa-link"></i></span>
                    <% end %>
                    <%= link_to edit_twit_path(twit), class: "level-item" do %>
                        <span class="icon"><i class="fa fa-pencil"></i></span>
                    <% end %>
                    <%= link_to twit, method: :delete, data: {confirm: "Are you sure you want to delete this twit?"} do %>
                        <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                    <% end %>
                    </div>
                
                </div>
            </div>
        </article>
    </div>
<% end %>

</div>

app/views/twits/_form.html.erb
<%= simple_form_for(@twit) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :twit, label: 'Twit it!', input_html: {class: "textarea"}, wrapper: false, 
    label_html: {class: "label"}, placeholder: 'Compose a new twit...'%>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/twits/_trends.html.erb
<div class="column is-one-quarter   ">
    <nav class="panel">
        <p class="panel-heading">
            Trends
        </p>
        <a class="panel-block">Trend 1</a>
        <a class="panel-block">Trend 2</a>
        <a class="panel-block">Trend 3</a>
        <a class="panel-block">Trend 4</a>
        <a class="panel-block">Trend 5</a>
    
    </nav>
</div>

app/views/twits/_twit.html.erb
<div id="<%= dom_id twit %>">
  <p>
    <strong>Twit:</strong>
    <%= twit.twit %>
  </p>

</div>

app/views/twits/_who_to_follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">
        Who To Follow
        </p>
    </nav>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong>A. Gunduz</strong>
                    <small>@ahmed_gun</small>
                </div>
            </div>
        </article>
    </div>
        <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong>A. Gunduz</strong>
                    <small>@ahmed_gun</small>
                </div>
            </div>
        </article>
    </div>
        <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong>A. Gunduz</strong>
                    <small>@ahmed_gun</small>
                </div>
            </div>
        </article>
    </div>
        <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong>A. Gunduz</strong>
                    <small>@ahmed_gun</small>
                </div>
            </div>
        </article>
    </div>
        <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/32x32.png">
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <strong>A. Gunduz</strong>
                    <small>@ahmed_gun</small>
                </div>
            </div>
        </article>
    </div>
</div>

app/views/twits/edit.html.erb
<div class="columns is-mobile is-centered">
  <div class="column is-half">
    <h1 class="has-text-weight-bold is-uppercase is-size-5">Edit your twit</h1>

    <%= render "form", twit: @twit %>

    <br>

    <div>
      <%= link_to "Show this twit", @twit %> |
      <%= link_to "Back to twits", twits_path %>
    </div>
  </div>
</div>

app/views/twits/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    <%= render 'trends' %>
    <%= render 'feed' %>
    <%= render 'who_to_follow' %>
    </div>
  </div>
</section>

app/views/twits/new.html.erb
<h1>New twit</h1>

<%= render "form", twit: @twit %>

<br>

<div>
  <%= link_to "Back to twits", twits_path %>
</div>

app/views/twits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @twit %>

<div>
  <%= link_to "Edit this twit", edit_twit_path(@twit) %> |
  <%= link_to "Back to twits", twits_path %>

  <%= button_to "Destroy this twit", @twit, method: :delete %>
</div>